server:
  port: 8081
  servlet:
    context-path: /mall-goods

min:
  info:
    base-package: com.miw.min.mall.goods.dal.mysql

--- #################### 数据库相关配置 ####################
spring:
  # 数据源配置项
  datasource:
    url: jdbc:mysql://localhost:3306/min-mall-goods?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456